### PR TITLE
Add basic continuous integration

### LINKED ISSUE #7: Test with CosmoSIS

### PR DESCRIPTION
**Pull request by itrharrison**
Currently only runs the tests for the standalone likelihood. I will also add tests on cosmosis and cobaya.

Merging will close #7 and #6

### CODE REVIEW

**Comment by itrharrison** [comment]
The above 10 commits taught me I should just go ahead and use tox straight away next time 😅

**Comment by itrharrison** [comment]
Just to clarify, the current behaviour of the (renamed) `remove_alens` parameter in this module and the `Alens` parameter passed to camb:

If
```
remove_alens = False
Alens = 1.2
```
Then both the primary CMB peaks are smeared and the clpp is rescaled in this lensing-only likelihood (i.e. the chi2 changes in the test).

If
```
remove_alens = True
Alens = 1.2
```
Then the primary CMB peaks are smeared and but the clpp is not rescaled in this lensing-only likelihood (i.e. the chi2 does not change in the test).

**Comment by msyriac** [comment]
Yes, that's how it should work. When the parameter was named "alens", I would set it to True if I was doing the Calabrese+-style Alens variation. I'm not sure I like the "remove_alens" renaming of it...

**Comment by msyriac** [comment]
How about "varying_cmb_alens" ?

**Pull request merged**
